@startuml
start
:Пользователь ввёл название и описание конференции;
:Пользователь задал список участников;
:Пользователь задал время конференции;
:Конференция запланирована и добавлена в список конференций;
:Конференция добавлена в календарь её создателя;
:Приглашения участникам отправлены;

if (Действие участника на приглашение?) then (Принял)
  :Приглашение помечено как принятое;
  :Конференция добавлена в календарь пользователя;
else (Отклонил)
  :Приглашение помечено как отклонённое;
  :Пользователь удалён из участников конференции;
 endif

:Создатель конференции начинает её;
:Система конференций создаёт ссылку для входа;
:Уведомления о начале конференции отправлены всем участникам (внутри ссылка для входа);
:Приглашённые участники заходят в конференцию по ссылке;
:Неприглашённый пользователь заходит в комнату ожидания конференции;
:Владелец конференции получает оповещение о пользователе в комнате ожидания;

if(Действия создателя конференции) then (Впустить пользователя)
    :Пользователь из комнаты ожидания добавлен в конференцию;
else (Отказать во входе)
    :Пользователь удаляется из комнаты ожидания;
endif

:Владелец конференции завершает её;
:Все участники удаляются из конференции;
:Все отсутствовавшие участники получают уведомление о том, что они пропустили конференцию;

stop
@enduml
